channels:
  - conda-forge
  - defaults

dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - cudatoolkit=11.8.0
  - faiss=1.7.4
  - libffi=3.4.2
  - libiconv=1.17
  - libsqlite=3.46.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - openssl=3.3.1
  - pip=24.0
  - python=3.8.19
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.2.6

  - pip:
      - absl-py==2.1.0
      - asgiref==3.8.1
      - asttokens==2.4.1
      - astunparse==1.6.3
      - backcall==0.2.0
      - backports-zoneinfo==0.2.1
      - cachetools==5.3.3
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.1.1
      - dill==0.3.8
      - django==4.2.13
      - django-cors-headers==4.4.0
      - djangorestframework==3.15.2
      - executing==2.0.1
      - filelock==3.14.0
      - flatbuffers==24.3.25
      - fonttools==4.53.0
      - fsspec==2024.5.0
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.31.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.64.1
      - h5py==3.11.0
      - idna==3.7
      - imageio==2.34.1
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.0
      - intel-openmp==2021.4.0
      - ipython==8.12.3
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - keras==2.13.1
      - kiwisolver==1.4.5
      - labelimg==1.8.6
      - lazy-loader==0.4
      - libclang==18.1.1
      - lmdb==1.4.1
      - lxml==5.2.2
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mkl==2021.4.0
      - mpmath==1.3.0
      - mtcnn==0.1.1
      - networkx==3.1
      - ninja==1.11.1.1
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opencv-contrib-python==4.10.0.84
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==2.0.3
      - parso==0.8.4
      - pickleshare==0.7.5
      - pillow==10.3.0
      - prompt-toolkit==3.0.46
      - protobuf==4.25.3
      - psutil==6.0.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - six==1.16.0
      - smmap==5.0.1
      - sqlparse==0.5.0
      - stack-data==0.6.3
      - sympy==1.12.1
      - tbb==2021.12.0
      - tensorboard==2.13.0
      - tensorflow==2.13.0
      - torchaudio==2.3.1+cu118
      - torchvision==0.18.1+cu118
