# Generated by Django 4.2.13 on 2024-09-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created',
        ),
    ]
