# Generated by Django 4.2.13 on 2024-09-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customuser", options={},),
        migrations.AlterModelManagers(name="customuser", managers=[],),
        migrations.RemoveField(model_name="customuser", name="date_joined",),
        migrations.RemoveField(model_name="customuser", name="first_name",),
        migrations.RemoveField(model_name="customuser", name="groups",),
        migrations.RemoveField(model_name="customuser", name="is_active",),
        migrations.RemoveField(model_name="customuser", name="is_staff",),
        migrations.RemoveField(model_name="customuser", name="is_superuser",),
        migrations.RemoveField(model_name="customuser", name="last_name",),
        migrations.RemoveField(model_name="customuser", name="user_permissions",),
        migrations.RemoveField(model_name="customuser", name="username",),
    ]
