# Generated by Django 4.2.13 on 2024-09-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
