# Generated by Django 4.2.13 on 2024-09-10 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 9, 10, 12, 15, 40, 806622, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
